title: Seungjoon Yoo
logo: /assets/img/2024_SeungjoonYoo.png
description: Ph.D. Candidate in Political Science at the University of Massachusetts Amherst

show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
