# Site Settings


locale: "en-US"
title: "Seungjoon Yoo"
title_separator          : "-"
name: "Seungjoon Yoo"
url : "https://seungjoonyoo.github.io"
baseurl                  : "/"




logo: /assets/img/2024_SeungjoonYoo.png

description: 'Ph.D. Candidate<br><br>Department of Political Science<br>University of Massachusetts Amherst<br><br><a href="https://scholar.google.com/citations?user=l74FPjIAAAAJ&hl=en">Google Scholar</a>'
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal